version: "3.7"
services:
  serverless:
    build: serverless
    entrypoint: bash
    env_file:
      - .env
    volumes:
      - ./:/ServerlessSpace
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
